Added Redux (with Toolkit) State Management for todoList itself and Filters for todoList.
gudzilla/ts-todoApp pull request #2
Opened 2024-08-02 18:25 UTC by gudzilla

2024-08-06 21:47 UTC, Muslik requested changes

2024-08-06 21:47 UTC, Muslik commented on src/components/todoList/TodoList.tsx
> +  let renderList = filterTodoListForRender(todoList, todoListFilter);
Неа. Это происходит в селекторе. read - createSelector.

Сами селекторы должны жить отдельно. То есть прям файлик с селекторами будет рядом с местом где объявлен стор.

Например:

```
const todoListSelector = (state: RootState) => state.todoList;

export const useTodoListSelector = () => useAppSelector(todoListSelector)
```

И `useTodoListSelector` ты уже будешь использовать.


`RootState` и RootDispatch` уедут куда нибудь в global.d.ts

Будет:
```
declare type RootState = ReturnType<typeof import('./index').store.getState>;
declare type RootDispatch = typeof import('./index').store.dispatch;
```
И получается эти два типа будут доступны всегда глобальны.

Далее у тебя появляется две функции - `useAppSelector` и `useAppDispatch`. Клади их куда нибудь в `shared/lib/redux`

```
export const useAppDispatch = () => useDispatch<RootDispatch>();
export const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;
```

Чтобы не надо было каждый раз добавлять типы. Везде будешь использовать теперь `useApp` хуки

2024-08-06 21:47 UTC, Muslik commented on src/states/todoFilters/filtersSlice.ts
> +    setFilter: (state, action: PayloadAction<{ filter: FilterNames }>) => {
Если `state` не используется, просто _

2024-08-06 21:47 UTC, Muslik commented on src/states/todoList/todoListSlice.ts
> +    toogleItemCheckbox: (state, action: PayloadAction<{ toggleId: string }>) => {
`toggleTodoDone`. Checkbox - ui-ный элемент.

2024-08-06 21:47 UTC, Muslik commented on src/states/todoList/todoListSlice.ts
> +    toggleAllCheckboxes: (state) => {
toggleAllDone

2024-08-06 21:47 UTC, Muslik commented on src/states/todoList/todoListSlice.ts
> +      return state.filter((todo) => todo.id !== removeId);
Тут filter, выше вместо map исполтзуешь find и мутацию. Я бы на одном варианте остановился

2024-08-06 21:47 UTC, Muslik commented on src/states/todoList/todoListSlice.ts
> +    editTodoName: (
changeTodo. Завтра будет меняться что нибудь еще и тебе придется переименовывать action.

2024-08-06 21:47 UTC, Muslik commented on src/states/todoList/todoListSlice.ts
> +import { TodoItem } from "../../types";
А представь у тебя еще 20 редьюсеров. Ты будешь просто свалку типов делать? Нет. Храни типы максимально близко к месту использования. По сути прям тут можешь оставить

2024-08-06 21:47 UTC, Muslik commented on src/constants/filters.ts
> +export type FilterNames = "all" | "active" | "completed";
Убирай это все из констант и уноси к слайсу. Он должен жить там, потому что относится именно к нему. Это штука работает с данными

2024-08-06 21:47 UTC, Muslik commented on src/components/todoList/TodoList.tsx
> +                onChange={(e) => {
`e` не используется

2024-08-06 21:47 UTC, Muslik commented on src/components/todoFilters/TodoFilters.tsx
> +        className={cx(styles.filter, { [styles.filterSelected]: filter === FILTERS.all })}
`nitpick`: А по сути это не кнопки - radio кнопки.
За раз может быть нажата только одна.

```
      <input
        type="radio"
        name="filter"
        value={FILTERS.all}
        checked={filter === FILTERS.all}
        onChange={({ target: { value } }) => {
          dispatch(setFilter({ filter: value }));
        }}
      />

```

2024-08-06 21:47 UTC, Muslik commented on src/components/addTodoForm/AddTodoForm.tsx
> +  function CompleteAllButton() {
Вынеси из компонента наверх. А вообще нет смысла в этом компоненте. Вставь сразу в разметку

2024-08-06 21:47 UTC, Muslik commented on src/components/addTodoForm/AddTodoForm.tsx
> +  const isListCompleted = todoList.every(FILTERS_PREDICATE[FILTERS.completed]);
Уезжает в селектор

2024-08-06 21:47 UTC, Muslik commented on src/components/addTodoForm/AddTodoForm.tsx
> +  const hasItems = todoList.length > 0;
В селектор. Дублируется даже в `TodoApp`

2024-08-08 07:45 UTC, gudzilla commented on src/components/todoFilters/TodoFilters.tsx
> +        className={cx(styles.filter, { [styles.filterSelected]: filter === FILTERS.all })}
Суть понял. Но там сейчас со стилями морочиться придется там свои нюансы. Так что проедем )

2024-08-08 07:46 UTC, gudzilla commented on src/components/addTodoForm/AddTodoForm.tsx
> +  function CompleteAllButton() {
Этот компонент сразу ниже применяется. Просто выписал в функцию чтобы читалось внизу проще. Или важнее чтобы был 1 компонент в 1 файле?

2024-11-06 10:13 UTC, merged